author: ${project.authors}
main: ${project.main}
version: ${version}
name: ${project.name}
description: ${project.description}
softdepend: ${project.softdepends}

commands:
  start:
    description: Spawn into the world.
    aliases: [begin]
  myz:
    description: Show help for MyZ.
  stats:
    description: Player statistics.
  blockallow:
    description: Allow breaking/placing of blocks.
    permission: MyZ.world_admin
  addresearchpoints:
    description: Adds research points.
    permission: MyZ.world_admin
  blocks:
    description: Block help.
  friend:
    description: Add a friend.
    permission: MyZ.friend
  friends:
    description: List friends.
  setlobby:
    description: Set the lobby region.
    permission: MyZ.world_admin
  addspawn:
    description: Add a spawnpoint.
    permission: MyZ.world_admin
  configure:
    description: Get the configuration for an item.
    permission: MyZ.*
  removespawn:
    description: Remove a spawnpoint.
    permission: MyZ.world_admin
    aliases: [delspawn]
  spawnpoints:
    description: List spawnpoints.
    aliases: [spawns]
  setresearch:
    description: Add researchables.
    permission: MyZ.scientist
    permission-message: Perhaps you meant /research?
  research:
    description: Research items.
  savemedkit:
    description: Save a MedKit.
    permission: MyZ.kit_admin
    aliases: [setmedkit, medkit]
    usage: /<command> <name>
  savekit:
    description: Save a starting kit.
    permission: MyZ.kit_admin
    aliases: [setkit]
  saverank:
    description: Set a chat prefix.
    permission: MyZ.admin
    aliases: [setrankprefix]
  setrank:
    description: Set a player's rank.
    permission: MyZ.admin
    aliases: [setplayerrank]
  joinclan:
    description: Join a clan.
    aliases: [createclan]
  clan:
    description: The name of your clan.
  getid:
    description: The ID for use on my-z.org.
  chestscan:
    description: Scan an area for chests.
    permission: MyZ.world_admin
  chestget:
    description: Get the lootset of a chest.
    permission: MyZ.world_admin
  chestset:
    description: Set the lootset of a chest.
    permission: MyZ.world_admin
  lootset:
    description: Set the contents of a lootset.
    permission: MyZ.world_admin
  mtranslate:
    description: Transpose a translation file.
    permission: MyZ.admin

permissions:
  MyZ.*:
    description: All things MyZ.
    default: op
    children:
      MyZ.admin: true
  MyZ.admin:
    description: All things MyZ.
    default: op
    children:
      MyZ.spawn_giant: true
      MyZ.world_admin: true
      MyZ.kit_admin: true
      MyZ.scientist: true
      MyZ.update: true
      MyZ.nokick: true
      MyZ.clan.*: true
  MyZ.spawn_giant:
    description: Spawn giants.
    default: op
  MyZ.kit_admin:
    description: All things kit-related.
    default: op
  MyZ.world_admin:
    description: All things world-related.
    default: op
  MyZ.scientist:
    description: Science commands.
    default: op
  MyZ.nokick:
    description: Don't get kicked on death.
    default: op
  MyZ.friend:
    description: Ability to add friends.
    default: true
  MyZ.clan.*:
    description: All things clan-related.
    default: op
  MyZ.clan.create:
    description: Ability to create a clan.
    default: op
  MyZ.clan.join:
    description: Ability to join clans.
    default: true
  MyZ.rank.0:
    description: The default rank.
    default: not op
  MyZ.rank.1:
    description: A rank.
    default: false
  MyZ.rank.2:
    description: A rank.
    default: false
  MyZ.rank.3:
    description: A rank.
    default: false
  MyZ.rank.4:
    description: A rank.
    default: false
  MyZ.rank.5:
    description: A rank.
    default: false
  MyZ.rank.6:
    description: A rank.
    default: false
  MyZ.rank.7:
    description: A rank.
    default: false
  MyZ.rank.8:
    description: A rank.
    default: false
  MyZ.rank.9:
    description: A rank.
    default: false
  MyZ.rank.10:
    description: A rank.
    default: false
  MyZ.rank.100:
    description: The OP rank.
    default: op